### ISSUE TITLE
Do not tell to "Specify the USB storage device by using USB_DEVICE"

### ISSUE THREAD

**Issue by jsmeix** [rear/rear-user-guide#2]
In
https://github.com/rear/rear-user-guide/blob/master/docs/basics/configuration.md
there is
```
OUTPUT=USB: Create a bootable USB disk (using extlinux). Specify the USB storage device by using USB_DEVICE.
```

I suggest to leave out the
"Specify the USB storage device by using USB_DEVICE"
because normally USB_DEVICE  gets set automatically for BACKUP=NETFS
via BACKUP_URL=usb:///dev/disk/by-label/REAR-000

I also suggest to remove (by the way) the
"(using extlinux)"
because meanwhile also GRUB is supported as bootloader on USB.

So I suggest that in the end that text becomes only
```
OUTPUT=USB: Create a bootable USB disk.
```
i.e. same as I did in
https://github.com/rear/rear/commit/2e9b1d34afafeb5b305f254bdc954b0be23e97e9

For the reason see
https://github.com/rear/rear/issues/2770#issuecomment-1068831482
and
https://github.com/rear/rear/commit/d615581577676d2e9201f1278d02e357273115f9
and why I report it here see
https://github.com/rear/rear/issues/2770#issuecomment-1069618378
```
https://relax-and-recover.org/rear-user-guide/basics/configuration.html

... please note that the "Rescue media (OUTPUT)" section of the same
document suggests manually setting USB_DEVICE.
```

**Comment by gdha** [comment]
@jsmeix Thanks for the review and update suggestions.
